### ISSUE TITLE
Can't login to Mendelson

### ISSUE THREAD

**Issue by danimbrogno** [savermyas/docker-mendelson-as2#3]
Hi! 

Thanks for this container. Unfortunately I can't seem to login to the Mendelson application. I get a prompt that asks me to login. The username defaults to admin and the password defaults to blank.

No matter what I enter here I can't seem to login. What should the password for admin be? Is this the same issue as #2 ?

<img width="1027" alt="screen shot 2018-01-04 at 2 16 33 pm" src="https://user-images.githubusercontent.com/2027311/34580156-eed23c50-f159-11e7-94d4-f8cf734b0151.png">

**Comment by cristiboariu** [comment]
@danimbrogno Have you found a way to login?

**Comment by cristiboariu** [comment]
@savermyas We also installed docker image but we are not able to login with admin/admin or guest/guest. Can you help please?

**Comment by savermyas** [comment]
@cristiboariu @danimbrogno I have updated the image to `v1.1b53`.
HTTP is working for me with `guest:guest` credentials.
VNC password is `qwerty`.
Please, try to update the image and re-run.

**Comment by savermyas** [comment]
Here are some screenshots of working Mendelson AS2 in container.

1) Connected via VNC:
![screen shot 2018-10-01 at 23 34 15](https://user-images.githubusercontent.com/1475688/46314321-df99c200-c5d2-11e8-97e0-e023c9768f2f.png)

2) Connected via HTTP (with information about successfull test message to Mendelson AS2 test server):
![screen shot 2018-10-01 at 23 39 18](https://user-images.githubusercontent.com/1475688/46314469-5636bf80-c5d3-11e8-8c45-9a3d5464add4.png)

3) My message on test server http://testas2.mendelson-e-c.com:8080/webas2/:
![screen shot 2018-10-01 at 23 35 05](https://user-images.githubusercontent.com/1475688/46314517-70709d80-c5d3-11e8-9a3b-6046b3453fd9.png)
