### ISSUE TITLE
Docker exit 1 when following readme

### ISSUE THREAD

**Issue by BT-panken** [savermyas/docker-mendelson-as2#4]
Following the readme with related requirement lead to following result:

    Name                   Command               State    Ports
    mendelson-as2    /bin/sh -c $MENDELSON_HOME ...               Exit 1    

Docker logs

> mendelson-as2 | Using data from previous run
> mendelson-as2 | Certificates storage not found. Creating default.
> mendelson-as2 | cp: cannot stat '/opt/mendelson/as2/certificates.p12': No such file or directory
> mendelson-as2 | Logging properties file not found. Creating default.
> mendelson-as2 | cp: cannot stat '/opt/mendelson/as2/log4j.properties': No such file or directory
> mendelson-as2 | Killing Xvnc process ID 50
> mendelson-as2 | Xvnc process ID 50 already killed
> mendelson-as2 | Xvnc did not appear to shut down cleanly. Removing /tmp/.X11-unix/X1
> mendelson-as2 | Xvnc did not appear to shut down cleanly. Removing /tmp/.X1-lock
> mendelson-as2 | Would you like to enter a view-only password (y/n)? A view-only password is not used
> mendelson-as2 | 
> mendelson-as2 | New '4a022fd01354:1 ()' desktop is 4a022fd01354:1
> mendelson-as2 | 
> mendelson-as2 | Starting applications specified in /root/.vnc/xstartup
> mendelson-as2 | Log file is /root/.vnc/4a022fd01354:1.log
> mendelson-as2 | 
> mendelson-as2 | Error: Could not find or load main class de.mendelson.comm.as2.AS2

**Comment by savermyas** [comment]
Please, check the latest version:
`saver/mendelson-as2:1.1b63`
